openapi: 3.0.0
info:
  title: Dissertation Registration API
  description: API for the Dissertation Registration App.
  version: 1.0.0
paths:
  /login:
    post:
      summary: User Login
      description: Authenticates a user by verifying their username and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user attempting to log in.
                password:
                  type: string
                  description: The password of the user attempting to log in.
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Login successful!'
        '400':
          description: Invalid username or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Invalid username or password!'
